//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wacton.Tovarisch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wacton.Tovarisch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   1 This software and database is being provided to you, the LICENSEE, by  
        ///  2 Princeton University under the following license.  By obtaining, using  
        ///  3 and/or copying this software and database, you agree that you have  
        ///  4 read, understood, and will comply with these terms and conditions.:  
        ///  5   
        ///  6 Permission to use, copy, modify and distribute this software and  
        ///  7 database and its documentation for any purpose and without fee or  
        ///  8 royalty is hereby granted, provided that you agree to comp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adjectives {
            get {
                return ResourceManager.GetString("Adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   1 This software and database is being provided to you, the LICENSEE, by  
        ///  2 Princeton University under the following license.  By obtaining, using  
        ///  3 and/or copying this software and database, you agree that you have  
        ///  4 read, understood, and will comply with these terms and conditions.:  
        ///  5   
        ///  6 Permission to use, copy, modify and distribute this software and  
        ///  7 database and its documentation for any purpose and without fee or  
        ///  8 royalty is hereby granted, provided that you agree to comp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adverbs {
            get {
                return ResourceManager.GetString("Adverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   1 This software and database is being provided to you, the LICENSEE, by  
        ///  2 Princeton University under the following license.  By obtaining, using  
        ///  3 and/or copying this software and database, you agree that you have  
        ///  4 read, understood, and will comply with these terms and conditions.:  
        ///  5   
        ///  6 Permission to use, copy, modify and distribute this software and  
        ///  7 database and its documentation for any purpose and without fee or  
        ///  8 royalty is hereby granted, provided that you agree to comp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nouns {
            get {
                return ResourceManager.GetString("Nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   1 This software and database is being provided to you, the LICENSEE, by  
        ///  2 Princeton University under the following license.  By obtaining, using  
        ///  3 and/or copying this software and database, you agree that you have  
        ///  4 read, understood, and will comply with these terms and conditions.:  
        ///  5   
        ///  6 Permission to use, copy, modify and distribute this software and  
        ///  7 database and its documentation for any purpose and without fee or  
        ///  8 royalty is hereby granted, provided that you agree to comp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Verbs {
            get {
                return ResourceManager.GetString("Verbs", resourceCulture);
            }
        }
    }
}
